--------------------------------------------------------
--  File created - Thursday-March-22-2018   
--------------------------------------------------------
-- REM INSERTING into TF_MARKETING_STATUS

Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (1,'MAPPED: TRAINING');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (2,'MAPPED: RESERVED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (3,'MAPPED: SELECTED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (4,'MAPPED: CONFIRMED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (5,'MAPPED: DEPLOYED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (6,'UNMAPPED: TRAINING');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (7,'UNMAPPED: OPEN');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (8,'UNMAPPED: SELECTED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (9,'UNMAPPED: CONFIRMED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (10,'UNMAPPED: DEPLOYED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (11,'DIRECTLY PLACED');
Insert into TF_MARKETING_STATUS (MARKETING_STATUS_ID,MARKETING_STATUS_NAME) values (12,'TERMINATED');
